apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rspamd.fullname" . }}
  labels:
    {{- include "rspamd.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rspamd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rspamd.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rspamd.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: proxy
              containerPort: {{ .Values.service.proxyPort }}
              protocol: TCP
            - name: rspamd
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: controller
              containerPort: {{ .Values.service.controllerPort }}
              protocol: TCP
            - name: fuzzy
              containerPort: {{ .Values.service.fuzzy }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/rspamd
          {{- if .Values.valkey.enabled }}
            - name: config
              mountPath: /etc/rspamd/local.d/redis.conf
              subPath: redis.conf
            - name: config
              mountPath: /etc/rspamd/local.d/history_redis.conf
              subPath: history_redis.conf
          {{- end }}
            - name: config
              mountPath: /etc/rspamd/local.d/worker-normal.inc
              subPath: worker-normal.inc
            - name: config
              mountPath: /etc/rspamd/local.d/worker-proxy.inc
              subPath: worker-proxy.inc
            - name: config
              mountPath: /etc/rspamd/local.d/dkim_signing.conf
              subPath: dkim_signing.conf
          {{- if .Values.arc.enabled }}
            - name: config
              mountPath: /etc/rspamd/local.d/arc.conf
              subPath: arc.conf
          {{- end }}
            - name: config
              mountPath: /etc/rspamd/local.d/milter_headers.conf
              subPath: milter_headers.conf
            - name: config
              mountPath: /etc/rspamd/local.d/classifier-bayes.conf
              subPath: classifier-bayes.conf
            - name: config
              mountPath: /etc/rspamd/override.d/classifier-bayes.conf
              subPath: override-classifier-bayes.conf
            - name: config
              mountPath: /etc/rspamd/local.d/multimap.conf
              subPath: multimap.conf
            - name: config
              mountPath: /etc/rspamd/local.d/whitelist_ip.map
              subPath: whitelist_ip.map
            - name: config
              mountPath: /etc/rspamd/local.d/whitelist_from.map
              subPath: whitelist_from.map
            - name: config
              mountPath: /etc/rspamd/local.d/blacklist_ip.map
              subPath: blacklist_ip.map
            - name: config
              mountPath: /etc/rspamd/local.d/blacklist_from.map
              subPath: blacklist_from.map

      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ default (include "rspamd.fullname" .) .Values.persistence.existingClaim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: config
          configMap:
            name: {{include "rspamd.fullname" .}}


      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
